# Generated by Django 4.0.1 on 2022-01-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gossip_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpsX', models.FloatField()),
                ('gpsY', models.FloatField()),
                ('zoneXY', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('writeDate', models.DateField()),
                ('kakaochat', models.CharField(max_length=50)),
                ('tokenID', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=20)),
                ('imageURL', models.CharField(max_length=50)),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('tokenID', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=10)),
                ('kakaochat', models.CharField(max_length=50)),
                ('joindate', models.DateField()),
                ('kakaoID', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiondata', models.CharField(max_length=200)),
                ('tokenID', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=20)),
                ('imageURL', models.CharField(max_length=50)),
                ('writeTime', models.DateTimeField()),
                ('gossip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.gossip_table')),
            ],
        ),
        migrations.AddField(
            model_name='gossip_table',
            name='userFID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.user_table'),
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerdata', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=20)),
                ('imageURL', models.CharField(max_length=50)),
                ('writeTime', models.DateTimeField()),
                ('questionFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.question')),
            ],
        ),
    ]
