# Generated by Django 4.0.1 on 2022-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_alter_gossip_table_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='imageURL',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='imageURL',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='imageUrl',
            field=models.CharField(max_length=200),
        ),
    ]
