# Generated by Django 4.0.1 on 2022-02-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_alter_answer_imageurl_alter_question_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gossip_table',
            name='zoneXY',
        ),
    ]
