# Generated by Django 4.0.1 on 2022-02-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_remove_gossip_table_zonexy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gossip_table',
            name='tokenID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gossip_table',
            name='writeDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='tokenID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='tokenID',
            field=models.CharField(max_length=200),
        ),
    ]
