# Generated by Django 4.0.1 on 2022-02-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_alter_gossip_table_tokenid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='messageonoff',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
